#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="60-load-images"
# CHANGE: Load per-image archives through the Docker wrapper and record local/archive/mirror sources.
SCRIPT_VERSION="4"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
UNKNOWN_ARGUMENTS=()
for argument in "$@"; do
	case "$argument" in
		--dry-run) DRY_RUN=true ;;
		*) UNKNOWN_ARGUMENTS+=("$argument") ;;
	esac
done
source "$SCRIPT_DIR/lib.sh"
begin_report
for argument in "${UNKNOWN_ARGUMENTS[@]}"; do
	step_fail "unknown argument: $argument" "Run learner-vm/scripts/60-load-images.sh [--dry-run]." "printf '%s\\n' --dry-run"
done
if ((EUID != 0)) && [[ "$DRY_RUN" == false ]]; then
	step_fail "image preparation requires root" "Run sudo learner-vm/scripts/60-load-images.sh after scripts 10-50." "id -u"
	end_report "rerun with sudo after the rootful Podman wrapper is installed"
	exit 1
elif ((EUID != 0)); then
	step_skip "rootful Podman execution requires root; dry-run continues" "rerun with sudo on the learner VM"
fi

commands_file="$REPO_ROOT/content/extracted/commands.json"
external_file="$REPO_ROOT/content/extracted/external-images.txt"
expected_file="$REPO_ROOT/content/extracted/build-failures-expected.txt"
manual_json="$REPO_ROOT/content/vendor/manual-fetch.json"
declare -a REQUIRED_IMAGES=()
declare -a LOCAL_BUILD_TAGS=()
IMAGE_REPORT_TMP=''
BUILT_TAGS_TMP=''
OUTPUT_LOG=''
UNEXPECTED_BUILD_FAILURES=0
cleanup() {
	[[ -z "$IMAGE_REPORT_TMP" ]] || rm -f -- "$IMAGE_REPORT_TMP"
	[[ -z "$BUILT_TAGS_TMP" ]] || rm -f -- "$BUILT_TAGS_TMP"
	[[ -z "$OUTPUT_LOG" ]] || rm -f -- "$OUTPUT_LOG"
}
trap cleanup EXIT

normalize_image() {
	local image="$1" first
	first="${image%%/*}"
	if [[ "$image" == */* ]]; then
		if [[ "$first" == *.* || "$first" == *:* || "$first" == localhost ]]; then printf '%s' "$image"; else printf 'docker.io/%s' "$image"; fi
	else
		printf 'docker.io/library/%s' "$image"
	fi
}

is_local_build_tag() {
	local image="$1" local_tag
	for local_tag in "${LOCAL_BUILD_TAGS[@]}"; do
		[[ "$image" == "$local_tag" || "$image" == "localhost/$local_tag" ]] && return 0
	done
	return 1
}

for file in "$commands_file" "$external_file" "$expected_file" "$manual_json" "$REPO_ROOT/content/extracted/curated.json"; do
	if [[ "$file" == "$expected_file" ]]; then
		[[ -f "$file" ]] && continue
	fi
	if [[ ! -s "$file" ]]; then
		step_fail "required image-preload metadata is missing: ${file#"$REPO_ROOT/"}" "Restore the repository ZIP generated by the connected packager." "ls -l $(printf '%q' "$file")" "find $(printf '%q' "$REPO_ROOT/content/extracted") -maxdepth 1 -type f -print"
	fi
done
if [[ -s "$expected_file" ]]; then
	while IFS= read -r expected_skip || [[ -n "$expected_skip" ]]; do
		[[ -n "$expected_skip" ]] || continue
		step_skip "recorded interactive build context is intentionally not run during preload" "$expected_skip"
	done < "$expected_file"
else
	step_ok "committed expected-build-skip inventory is present and empty"
fi
if ! command -v python3 >/dev/null 2>&1; then
	step_fail "python3 is required to read commands.json" "Install python3 with scripts/20-install-tooling.sh before loading images." "command -v python3" "rpm -q python3"
fi
mapfile -t LOCAL_BUILD_TAGS < <(python3 -c 'import json,sys; data=json.load(open(sys.argv[1],encoding="utf-8")); print("\n".join(sorted({command["tag"] for track in data.values() for lab in track.get("labs",[]) for command in lab.get("commands",[]) if command.get("type")=="build" and command.get("tag")})))' "$commands_file")

if [[ -s "$external_file" ]]; then
	while IFS= read -r image || [[ -n "$image" ]]; do
		image="${image%%#*}"
		image="$(printf '%s' "$image" | tr -d '[:space:]')"
		[[ -n "$image" ]] || continue
		REQUIRED_IMAGES+=("$(normalize_image "$image")")
	done < "$external_file"
fi

curated_images=$(python3 - "$REPO_ROOT/content/extracted/curated.json" <<'PY'
import json
import sys
with open(sys.argv[1], encoding="utf-8") as source:
    data = json.load(source)
images = set()
for track in data.values():
    for run in track.get("runs", []):
        if run.get("requires_k3s"):
            continue
        for key in ("image", "images"):
            value = run.get(key, [])
            if isinstance(value, str):
                value = [value]
            if isinstance(value, list):
                images.update(item for item in value if isinstance(item, str) and item)
print("\n".join(sorted(images)))
PY
)
while IFS= read -r image; do
	[[ -n "$image" ]] || continue
	if is_local_build_tag "$image" || [[ "$image" == localhost/* ]]; then REQUIRED_IMAGES+=("$image"); else REQUIRED_IMAGES+=("$(normalize_image "$image")"); fi
done <<< "$curated_images"
mapfile -t REQUIRED_IMAGES < <(printf '%s\n' "${REQUIRED_IMAGES[@]}" | sort -u)

if ! load_image_archives podman; then
	end_report "Correct the local image archive described in MANUAL-FETCH.md Section C before retrying; no image pulls were attempted."
	exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
	log "external references are pulled through the configured Artifactory mirror; no image bundle transfer is required"
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]] || is_local_build_tag "$image"; then
			log "local manifest image is never pulled externally: $image"
		else
			log "would check rootful Podman store, then podman pull if missing: $image"
		fi
	done
else
	for tool in podman sha256sum; do
		if ! command -v "$tool" >/dev/null 2>&1; then
			step_fail "$tool is unavailable" "Run scripts/20-install-tooling.sh before loading workshop images." "command -v $(printf %q "$tool")" "rpm -q $(printf %q "$tool")"
		fi
	done
	rootless_state="$(podman info --format '{{.Host.Security.Rootless}}' 2>/dev/null || printf 'unknown')"
	if [[ "$rootless_state" == false ]]; then
		step_ok "Podman is using the rootful image store"
	else
		step_fail "Podman is not confirmed rootful (state: $rootless_state)" "Run through the script 50 wrapper using sudo and retain the shared rootful image store." "podman info --debug 2>&1 | tail -n 20" "id"
	fi
fi

if [[ "$DRY_RUN" == true ]]; then
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]]; then log "would build locally from its recorded context and verify exact manifest reference: $image"; fi
	done
	python3 -c '
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: data=json.load(source)
for track,track_data in data.items():
	for lab in track_data.get("labs",[]):
		for command in lab.get("commands",[]):
			if command.get("type") == "build":
				print("track={track} lab={lab} engine={engine} cwd={cwd} context={context} dockerfile={dockerfile} tag={tag} status={status}".format(track=track,lab=lab.get("file",""),engine=command.get("engine",""),cwd=command.get("cwd","."),context=command.get("context",""),dockerfile=command.get("dockerfile_arg") or command.get("dockerfile",""),tag=command.get("tag") or "<untagged>",status=command.get("preload_status","INTERACTIVE")))
				for step in command.get("preload_steps",[]): print("step="+step)
' "$commands_file" | while IFS= read -r build_line; do log "dry-run build $build_line"; done
fi

if [[ "$DRY_RUN" == false ]]; then
	OUTPUT_LOG=$(mktemp "${TMPDIR:-/tmp}/60-load-images.XXXXXX")
	IMAGE_REPORT_TMP=$(mktemp "${TMPDIR:-/tmp}/podman-images.XXXXXX")
	BUILT_TAGS_TMP=$(mktemp "${TMPDIR:-/tmp}/built-tags.XXXXXX")
	printf 'image | source | result | detail\n' > "$IMAGE_REPORT_TMP"
	printf 'track | lab | tag | status | source\n' > "$BUILT_TAGS_TMP"
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]] || is_local_build_tag "$image"; then
			if podman image exists "$image" >/dev/null 2>&1; then
				step_ok "locally built manifest image is present: $image"
				printf '%s | manifest | present | exact local reference\n' "$image" >> "$IMAGE_REPORT_TMP"
			elif is_local_build_tag "$image"; then
				step_skip "recorded local build tag will be processed from commands.json" "$image"
			else
				if podman image exists "${image#localhost/}" >/dev/null 2>&1; then
					step_skip "local image exists only without manifest localhost prefix" "script 62 will import the existing tag and verify the original manifest reference: $image"
				else
					step_skip "local manifest image will be built from commands.json preload_steps" "$image"
				fi
			fi
		elif podman image exists "$image" >/dev/null 2>&1; then
			step_ok "external image already present: $image"
			source="${LOCAL_ARCHIVE_IMAGES[$image]:-existing store}"
			printf '%s | %s | present | original reference verified\n' "$image" "$source" >> "$IMAGE_REPORT_TMP"
			printf 'external | - | %s | present | %s\n' "$image" "$source" >> "$BUILT_TAGS_TMP"
		else
			pull_log=$(mktemp "${TMPDIR:-/tmp}/60-pull.XXXXXX")
			if podman pull "$image" >"$pull_log" 2>&1; then
				step_ok "Podman pull command succeeded for $image"
				printf '%s | Artifactory mirror | pulled | command returned success\n' "$image" >> "$IMAGE_REPORT_TMP"
				printf 'external | - | %s | pulled | Artifactory mirror\n' "$image" >> "$BUILT_TAGS_TMP"
			else
				pull_status=$?
				if [[ -w "$LOG_FILE" || -w "$(dirname "$LOG_FILE")" ]]; then { printf '[%s] pull output for %s (exit %s)\n' "$SCRIPT_NAME" "$image" "$pull_status"; cat "$pull_log"; } >> "$LOG_FILE" 2>/dev/null || true; fi
				printf '%s | pull | failed | exit %s\n' "$image" "$pull_status" >> "$IMAGE_REPORT_TMP"
				printf 'external | - | %s | FAILED | Artifactory mirror\n' "$image" >> "$BUILT_TAGS_TMP"
				registry_pull_result "$image" "$pull_status" "$(cat "$pull_log")" 0 false
				step_skip "expected local image path: $MANUAL_FETCH_DIR/images/$(image_asset_name "$image")" "MANUAL-FETCH.md Section C recovery"
			fi
			rm -f -- "$pull_log"
			if ! podman image exists "$image" >/dev/null 2>&1; then
				step_fail "image is absent after local-archive loading and mirror pull: $image" "See MANUAL-FETCH.md Section C; stage $MANUAL_FETCH_DIR/images/$(image_asset_name "$image") and retry." "podman images --no-trunc"
			fi
		fi
	done

	while IFS= read -r record; do
		fields=$(python3 - "$record" <<'PY'
import json
import sys
item=json.loads(sys.argv[1])
print(item.get("track", ""))
print(item.get("lab", ""))
print(item.get("tag") or "")
print(item.get("preload_status", "INTERACTIVE"))
print(item.get("engine", ""))
print(item.get("cwd", "."))
print(item.get("context", ""))
print(item.get("dockerfile_arg") or item.get("dockerfile", ""))
print(item.get("raw", ""))
print(json.dumps(item.get("preload_steps", [])))
print(json.dumps(item.get("base_images", [])))
PY
)
		mapfile -t build_fields <<< "$fields"
		track="${build_fields[0]}"; lab="${build_fields[1]}"; tag="${build_fields[2]}"; status="${build_fields[3]}"; engine="${build_fields[4]}"; cwd="${build_fields[5]}"; context="${build_fields[6]}"; dockerfile="${build_fields[7]}"; raw="${build_fields[8]}"; steps_json="${build_fields[9]}"; bases_json="${build_fields[10]}"
		log "build record track=$track lab=$lab engine=$engine cwd=$cwd context=$context dockerfile=$dockerfile tag=${tag:-untagged}"
		if [[ "$status" == INTERACTIVE ]]; then
			base_images=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$bases_json")
			while IFS= read -r base; do
				[[ -n "$base" ]] || continue
				base="$(normalize_image "$base")"
				if podman image exists "$base" >/dev/null 2>&1; then
					step_ok "interactive build base image is preloaded: $base"
				else
					step_fail "interactive build base image is absent: $base" "Pull the tagged base through the configured Artifactory mirror using podman pull; no image bundle transfer is required." "podman image exists $(printf %q "$base")" "podman pull $(printf %q "$base")" "grep -F $(printf %q "$base") $(printf %q "$external_file")"
				fi
			done <<< "$base_images"
			step_skip "interactive build was not invoked" "$track/$lab: $raw"
			printf '%s | %s | %s | INTERACTIVE (not run) | local build\n' "$track" "$lab" "${tag:-untagged}" >> "$BUILT_TAGS_TMP"
			continue
		fi
		if [[ "$status" != PRELOADABLE-VIA-VENDORED-CONTEXT && "$status" != PRELOADABLE-VIA-VENDORED-DOWNLOAD && "$status" != BUILT-PRELOADABLE ]]; then
			step_fail "build record has unsupported preload status $status" "Refresh commands.json with scripts/dev/parse-labs.py and inspect source record $track/$lab." "grep -n $(printf %q "$lab") $(printf %q "$commands_file")"
			((UNEXPECTED_BUILD_FAILURES += 1))
			continue
		fi
		if [[ -n "$tag" ]] && podman image exists "$tag" >/dev/null 2>&1; then
			step_ok "recorded preload tag is already present: $tag"
			printf '%s | %s | %s | ALREADY-PRESENT (build skipped) | existing store\n' "$track" "$lab" "$tag" >> "$BUILT_TAGS_TMP"
			continue
		fi
		base_images=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$bases_json")
		while IFS= read -r base; do
			[[ -n "$base" ]] || continue
			base="$(normalize_image "$base")"
			if is_local_build_tag "$base" || [[ "$base" == localhost/* ]]; then continue; fi
			if ! podman image exists "$base" >/dev/null 2>&1; then
				step_fail "base image required by $track/$lab is absent: $base" "Ensure the tagged external base is in external-images.txt and pull it through the configured Artifactory mirror." "podman image exists $(printf %q "$base")" "podman pull $(printf %q "$base")" "grep -F $(printf %q "$base") $(printf %q "$external_file")"
			fi
		done <<< "$base_images"
		steps=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$steps_json")
		if [[ -z "$steps" ]]; then
			step_fail "preloadable build has no recorded preload_steps: $track/$lab" "Regenerate commands.json with scripts/dev/parse-labs.py and inspect this build record." "grep -n $(printf %q "$lab") $(printf %q "$commands_file")"
			((UNEXPECTED_BUILD_FAILURES += 1))
			continue
		fi
		build_failed=false
		build_cwd="$REPO_ROOT/content/repos/$track/$cwd"
		while IFS= read -r build_step; do
			[[ -n "$build_step" ]] || continue
			if [[ "$build_step" == extract\ * ]]; then
				archive="${build_step#extract }"; archive="${archive%% to *}"
				destination_text="${build_step#* to }"; destination_text="${destination_text%% (archive root*}"
				archive_root="${build_step##*archive root }"; archive_root="${archive_root%)}"
				expected_archive_sha=$(python3 - "$manual_json" "$archive" <<'PY'
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: entries=json.load(source)
entry=next((row for row in entries if row.get("category")=="repo" and row.get("name")==sys.argv[2]),None)
print(entry.get("sha256", "") if entry else "")
PY
)
				archive_path="$REPO_ROOT/$archive"
				if [[ ! -s "$archive_path" || ! "$expected_archive_sha" =~ ^[0-9a-f]{64}$ ]]; then
					step_fail "runtime context archive is unavailable or unpinned: $archive" "Restore the repo ZIP and manual-fetch entry before building $track/$lab." "ls -l $(printf %q "$archive_path")" "grep -F $(printf %q "$archive") $(printf %q "$manual_json")"
					((UNEXPECTED_BUILD_FAILURES += 1))
					continue
				fi
				actual_archive_sha=$(sha256sum "$archive_path" | awk '{print $1}')
				if [[ "$actual_archive_sha" != "$expected_archive_sha" ]]; then
					step_fail "runtime context archive checksum mismatch: $archive" "Restore the verified archive from the repository ZIP." "sha256sum $(printf %q "$archive_path")" "grep -F $(printf %q "$archive") $(printf %q "$manual_json")"
					((UNEXPECTED_BUILD_FAILURES += 1))
					continue
				fi
				extract_dir="$REPO_ROOT/$destination_text"
				if unzip -tq "$archive_path" >/dev/null 2>&1 && unzip -oq "$archive_path" -d "$extract_dir"; then
					step_ok "verified and extracted runtime context archive root $archive_root for $track/$lab"
				else
					step_fail "could not extract verified runtime context archive $archive" "Check disk space and the archive root in commands.json." "unzip -t $(printf %q "$archive_path")" "df -hP $(printf %q "$extract_dir")"
					((UNEXPECTED_BUILD_FAILURES += 1))
				fi
			else
				if [[ "$build_step" == *"content/repos/"* ]]; then build_cwd="$REPO_ROOT"; fi
				if bash -c "cd $(printf %q "$build_cwd") && $build_step" >"$OUTPUT_LOG" 2>&1; then
					step_ok "preload build completed for $track/$lab: ${tag:-untagged}"
				else
					build_status=$?
					build_failed=true
					if [[ -w "$LOG_FILE" || -w "$(dirname "$LOG_FILE")" ]]; then { printf '[%s] build output for %s/%s command=%s (exit %s)\n' "$SCRIPT_NAME" "$track" "$lab" "$build_step" "$build_status"; cat "$OUTPUT_LOG"; } >> "$LOG_FILE" 2>/dev/null || true; fi
					printf 'BUILD FAILURE %s/%s tag=%s engine=%s cwd=%s status=%s command=%s\n' "$track" "$lab" "${tag:-untagged}" "$engine" "$cwd" "$build_status" "$build_step" >> "$IMAGE_REPORT_TMP"
					step_fail "preload build failed for $track/$lab: ${tag:-untagged} (exit $build_status)" "Inspect the vendored build context and original command recorded for $track/$lab; do not edit upstream sources during preload." "tail -n 15 $(printf %q "$OUTPUT_LOG")" "podman images --no-trunc | head -n 20"
					((UNEXPECTED_BUILD_FAILURES += 1))
				fi
			fi
		done <<< "$steps"
		if [[ "$build_failed" == true ]]; then
			printf '%s | %s | %s | BUILD-FAILED (see %s) | local build\n' "$track" "$lab" "${tag:-untagged}" "$LOG_FILE" >> "$BUILT_TAGS_TMP"
			continue
		fi
		if [[ -n "$tag" ]]; then
			if podman image exists "$tag" >/dev/null 2>&1; then
				printf '%s | %s | %s | %s | local build\n' "$track" "$lab" "$tag" "$status" >> "$BUILT_TAGS_TMP"
				printf '%s | build | present | %s %s\n' "$tag" "$track" "$lab" >> "$IMAGE_REPORT_TMP"
			else
				step_fail "recorded build did not produce tag $tag for $track/$lab" "Compare the exact preload_steps and source files in commands.json; interactive builds are not invoked." "podman image exists $(printf %q "$tag")" "tail -n 15 $(printf %q "$OUTPUT_LOG")"
				((UNEXPECTED_BUILD_FAILURES += 1))
			fi
		fi
	done < <(python3 - "$commands_file" <<'PY'
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: data=json.load(source)
for track,track_data in data.items():
    for lab in track_data.get("labs",[]):
        for command in lab.get("commands",[]):
            if command.get("type")=="build":
                print(json.dumps({"track":track,"lab":lab.get("file",""),**command},separators=(",",":")))
PY
)

	manifest_path="$REPO_ROOT/content/repos/opentelemetry/_vendored/app_pod.yaml"
	manifest_image="$(awk '/^[[:space:]]*image:[[:space:]]*/ {sub(/^[[:space:]]*image:[[:space:]]*/, ""); print; exit}' "$manifest_path" 2>/dev/null || true)"
	if [[ -n "$manifest_image" ]]; then
		if podman image exists "$manifest_image" >/dev/null 2>&1; then
			step_ok "exact OpenTelemetry Pod manifest image exists in Podman: $manifest_image"
		elif podman image exists "${manifest_image#localhost/}" >/dev/null 2>&1; then
			local_source="${manifest_image#localhost/}"
			if run "podman tag $(printf %q "$local_source") $(printf %q "$manifest_image")" && podman image exists "$local_source" >/dev/null 2>&1 && podman image exists "$manifest_image" >/dev/null 2>&1; then
				step_ok "tagged the locally built image with the exact manifest reference $manifest_image"
			else
				step_fail "could not create/verify required manifest tag $manifest_image" "Use the exact local image source required by the vendored Pod manifest; preserve and verify both references." "podman image inspect $(printf %q "$local_source")" "podman image inspect $(printf %q "$manifest_image")" "grep -n 'image:' $(printf %q "$manifest_path")"
				((UNEXPECTED_BUILD_FAILURES += 1))
			fi
		else
			step_fail "OpenTelemetry Pod manifest image is absent: $manifest_image" "Build the recorded hello-otel:prog context and add the exact manifest reference; never try to pull localhost as external." "podman image exists $(printf %q "$manifest_image")" "grep -n 'image:' $(printf %q "$manifest_path")"
			((UNEXPECTED_BUILD_FAILURES += 1))
		fi
	fi

	install -o root -g root -m 0644 "$IMAGE_REPORT_TMP" "$REPO_ROOT/content/extracted/podman-load-report.txt"
	install -o root -g root -m 0644 "$BUILT_TAGS_TMP" "$REPO_ROOT/content/extracted/built-tags.txt"
	step_ok "wrote content/extracted/podman-load-report.txt and built-tags.txt"
fi

end_report "Review required image/build failures; after fixing them, continue with scripts/62-k3s-images.sh."
if ((UNEXPECTED_BUILD_FAILURES > 0)); then exit 2; fi
((FAIL_COUNT == 0))
