#!/usr/bin/env bash
set -euo pipefail

SCRIPT_NAME="60-load-images"
# CHANGE: Import checksum-verified aggregate dependency bundle images and profiles before per-image recovery.
SCRIPT_VERSION="7"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
UNKNOWN_ARGUMENTS=()
for argument in "$@"; do
	case "$argument" in
		--dry-run) DRY_RUN=true ;;
		*) UNKNOWN_ARGUMENTS+=("$argument") ;;
	esac
done
source "$SCRIPT_DIR/lib.sh"
begin_report
for argument in "${UNKNOWN_ARGUMENTS[@]}"; do
	step_fail "unknown argument: $argument" "Run learner-vm/scripts/60-load-images.sh [--dry-run]." "printf '%s\\n' --dry-run"
done
if ((EUID != 0)) && [[ "$DRY_RUN" == false ]]; then
	step_fail "image preparation requires root" "Run sudo learner-vm/scripts/60-load-images.sh after scripts 10-50." "id -u"
	end_report "rerun with sudo after the rootful Podman wrapper is installed"
	exit 1
elif ((EUID != 0)); then
	step_skip "rootful Podman execution requires root; dry-run continues" "rerun with sudo on the learner VM"
fi

commands_file="$REPO_ROOT/content/extracted/commands.json"
external_file="$REPO_ROOT/content/extracted/external-images.txt"
expected_file="$REPO_ROOT/content/extracted/build-failures-expected.txt"
manual_json="$REPO_ROOT/content/vendor/manual-fetch.json"
declare -a REQUIRED_IMAGES=()
declare -a LOCAL_BUILD_TAGS=()
IMAGE_REPORT_TMP=''
BUILT_TAGS_TMP=''
OUTPUT_LOG=''
DEPENDENCY_CACHE_STAGE=''
PROFILE_SELECTOR_TMP=''
UNEXPECTED_BUILD_FAILURES=0
cleanup() {
	[[ -z "$IMAGE_REPORT_TMP" ]] || rm -f -- "$IMAGE_REPORT_TMP"
	[[ -z "$BUILT_TAGS_TMP" ]] || rm -f -- "$BUILT_TAGS_TMP"
	[[ -z "$OUTPUT_LOG" ]] || rm -f -- "$OUTPUT_LOG"
	[[ -z "$DEPENDENCY_CACHE_STAGE" ]] || rm -rf -- "$DEPENDENCY_CACHE_STAGE"
	[[ -z "$PROFILE_SELECTOR_TMP" ]] || rm -f -- "$PROFILE_SELECTOR_TMP"
}
trap cleanup EXIT

normalize_image() {
	local image="$1" first
	first="${image%%/*}"
	if [[ "$image" == */* ]]; then
		if [[ "$first" == *.* || "$first" == *:* || "$first" == localhost ]]; then printf '%s' "$image"; else printf 'docker.io/%s' "$image"; fi
	else
		printf 'docker.io/library/%s' "$image"
	fi
}

is_local_build_tag() {
	local image="$1" local_tag
	for local_tag in "${LOCAL_BUILD_TAGS[@]}"; do
		[[ "$image" == "$local_tag" || "$image" == "localhost/$local_tag" ]] && return 0
	done
	return 1
}

for file in "$commands_file" "$external_file" "$expected_file" "$manual_json" "$REPO_ROOT/content/extracted/curated.json"; do
	if [[ "$file" == "$expected_file" ]]; then
		[[ -f "$file" ]] && continue
	fi
	if [[ ! -s "$file" ]]; then
		step_fail "required image-preload metadata is missing: ${file#"$REPO_ROOT/"}" "Restore the repository ZIP generated by the connected packager." "ls -l $(printf '%q' "$file")" "find $(printf '%q' "$REPO_ROOT/content/extracted") -maxdepth 1 -type f -print"
	fi
done
if [[ -s "$expected_file" ]]; then
	while IFS= read -r expected_skip || [[ -n "$expected_skip" ]]; do
		[[ -n "$expected_skip" ]] || continue
		step_skip "recorded interactive build context is intentionally not run during preload" "$expected_skip"
	done < "$expected_file"
else
	step_ok "committed expected-build-skip inventory is present and empty"
fi
if ! command -v python3 >/dev/null 2>&1; then
	step_fail "python3 is required to read commands.json" "Install python3 with scripts/20-install-tooling.sh before loading images." "command -v python3" "rpm -q python3"
fi
mapfile -t LOCAL_BUILD_TAGS < <(python3 -c 'import json,sys; data=json.load(open(sys.argv[1],encoding="utf-8")); print("\n".join(sorted({command["tag"] for track in data.values() for lab in track.get("labs",[]) for command in lab.get("commands",[]) if command.get("type")=="build" and command.get("tag")})))' "$commands_file")

if [[ -n "${DEPENDENCY_BUNDLE_SHA256:-}" ]]; then
	if [[ ! "$DEPENDENCY_BUNDLE_SHA256" =~ ^[0-9a-f]{64}$ ]]; then
		step_fail "DEPENDENCY_BUNDLE_SHA256 is invalid" "Set it to the trusted 64-character SHA-256 published through the approved release channel." "grep '^DEPENDENCY_BUNDLE_SHA256=' $(printf '%q' "$CONFIG_FILE")"
		end_report "Correct the trusted bundle checksum before importing dependencies."
		exit 1
	fi
	if [[ ! -s "$DEPENDENCY_BUNDLE_PATH" ]]; then
		step_fail "configured dependency bundle is missing" "Transfer the release archive to DEPENDENCY_BUNDLE_PATH using the approved process." "ls -l $(printf '%q' "$DEPENDENCY_BUNDLE_PATH")"
		end_report "Stage the separately transferred bundle before image preparation."
		exit 1
	fi
	bundle_version_root="$DEPENDENCY_BUNDLE_ROOT/$DEPENDENCY_BUNDLE_SHA256"
	if [[ "$DRY_RUN" == true ]]; then
		python3 "$REPO_ROOT/learner-vm/dependency_bundle.py" verify --archive "$DEPENDENCY_BUNDLE_PATH" --sha256 "$DEPENDENCY_BUNDLE_SHA256"
		log "[dry-run] WOULD install the verified bundle at $bundle_version_root, load its aggregate images, and generate offline package profiles"
		step_skip "aggregate image load and package profile activation were not performed during dry-run" "$bundle_version_root"
	else
		if ! python3 "$REPO_ROOT/learner-vm/dependency_bundle.py" verify --archive "$DEPENDENCY_BUNDLE_PATH" --sha256 "$DEPENDENCY_BUNDLE_SHA256" --destination "$bundle_version_root"; then
			step_fail "dependency bundle checksum, inventory, or safe extraction verification failed" "Correct the staged release asset or trusted checksum; the active bundle and image store were not intentionally replaced." "sha256sum $(printf '%q' "$DEPENDENCY_BUNDLE_PATH")" "ls -ld $(printf '%q' "$bundle_version_root")"
			end_report "Review the bundle verification failure before retrying image preparation."
			exit 1
		fi
		learner_passwd="$(getent passwd "$WORKSHOP_USER" 2>/dev/null || true)"
		learner_home="${learner_passwd##*:}"
		learner_group="$(id -gn "$WORKSHOP_USER" 2>/dev/null || true)"
		if [[ -z "$learner_passwd" || -z "$learner_group" || ! -d "$learner_home" || -L "$learner_home" ]]; then
			step_fail "configured WORKSHOP_USER home is unavailable or unsafe for package-cache seeding" "Restore the learner account/home before importing writable package caches." "getent passwd $(printf '%q' "$WORKSHOP_USER")" "ls -ld $(printf '%q' "$learner_home")"
			end_report "Correct WORKSHOP_USER before activating package caches."
			exit 1
		fi
		working_cache_root="$learner_home/.cache/o11y-lab/$DEPENDENCY_BUNDLE_SHA256"
		cache_marker="$working_cache_root/.bundle-sha256"
		if [[ -e "$working_cache_root" || -L "$working_cache_root" ]]; then
			if [[ -L "$working_cache_root" || ! -d "$working_cache_root" || -L "$cache_marker" || ! -f "$cache_marker" || "$(<"$cache_marker")" != "$DEPENDENCY_BUNDLE_SHA256" ]]; then
				step_fail "existing writable dependency cache is not marked for this verified bundle" "Preserve existing data and inspect $working_cache_root; do not delete it automatically." "ls -ld $(printf '%q' "$working_cache_root")" "cat $(printf '%q' "$cache_marker")"
				end_report "Resolve the existing cache directory before installing this bundle's package profiles."
				exit 1
			fi
			step_ok "reusing writable package caches seeded from this verified bundle"
		else
			cache_parent="$(dirname "$working_cache_root")"
			if [[ -L "$learner_home/.cache" || -L "$cache_parent" ]]; then
				step_fail "learner package-cache path contains a symbolic link" "Preserve existing data and configure a real learner-owned .cache/o11y-lab directory." "ls -ld $(printf '%q' "$learner_home/.cache") $(printf '%q' "$cache_parent")"
				end_report "Replace the package-cache symlink with an operator-reviewed directory before import."
				exit 1
			fi
			if [[ ! -e "$cache_parent" ]] && ! install -d -o "$WORKSHOP_USER" -g "$learner_group" -m 0700 "$cache_parent"; then
				step_fail "could not prepare the learner-owned package-cache directory" "Check learner home ownership and free disk space; bundle caches remain untouched." "ls -ld $(printf '%q' "$learner_home/.cache") $(printf '%q' "$cache_parent")" "df -hP $(printf '%q' "$learner_home")"
				end_report "Restore writable learner cache storage before activating package profiles."
				exit 1
			fi
			if [[ ! -d "$cache_parent" || "$(stat -c '%u' "$cache_parent")" != "$(id -u "$WORKSHOP_USER")" ]]; then
				step_fail "existing learner package-cache parent is not a learner-owned directory" "Preserve existing contents and ask the operator to repair ownership of $cache_parent." "stat -c '%U:%G %a %n' $(printf '%q' "$cache_parent")"
				end_report "Correct cache-parent ownership before installing writable dependency caches."
				exit 1
			fi
			DEPENDENCY_CACHE_STAGE="$(mktemp -d "$cache_parent/.bundle-cache.XXXXXX")" || DEPENDENCY_CACHE_STAGE=''
			if [[ -z "$DEPENDENCY_CACHE_STAGE" ]] || ! mkdir -p "$DEPENDENCY_CACHE_STAGE/maven" "$DEPENDENCY_CACHE_STAGE/npm" "$DEPENDENCY_CACHE_STAGE/go/pkg/mod" ||
				! cp -a --no-preserve=ownership "$bundle_version_root/cache/maven/repository/." "$DEPENDENCY_CACHE_STAGE/maven/" ||
				! cp -a --no-preserve=ownership "$bundle_version_root/cache/npm/." "$DEPENDENCY_CACHE_STAGE/npm/" ||
				! cp -a --no-preserve=ownership "$bundle_version_root/cache/go/pkg/mod/." "$DEPENDENCY_CACHE_STAGE/go/pkg/mod/" ||
				! chown -R "$WORKSHOP_USER:$learner_group" "$DEPENDENCY_CACHE_STAGE" ||
				! printf '%s\n' "$DEPENDENCY_BUNDLE_SHA256" > "$DEPENDENCY_CACHE_STAGE/.bundle-sha256" ||
				! chown "$WORKSHOP_USER:$learner_group" "$DEPENDENCY_CACHE_STAGE/.bundle-sha256" ||
				! chmod 0600 "$DEPENDENCY_CACHE_STAGE/.bundle-sha256" ||
				! mv -- "$DEPENDENCY_CACHE_STAGE" "$working_cache_root"; then
				step_fail "could not seed writable learner Maven/npm/Go caches from the verified bundle" "Check free space and learner-home permissions; the immutable bundle remains unchanged." "df -hP $(printf '%q' "$learner_home")" "ls -ld $(printf '%q' "$cache_parent")"
				end_report "Repair learner cache storage and rerun the idempotent import."
				exit 1
			fi
			DEPENDENCY_CACHE_STAGE=''
			step_ok "seeded versioned writable Maven/npm/Go caches for $WORKSHOP_USER"
		fi
		if ! docker load -i "$bundle_version_root/images/lab-images.tar"; then
			step_fail "could not load aggregate lab image archive into rootful Podman" "Check free disk space and the verified bundle image archive; no registry fallback is used for a corrupt aggregate archive." "df -hP /var/lib/containers" "podman info --debug 2>&1 | tail -n 15"
			end_report "Resolve aggregate image import failure before continuing with per-image recovery."
			exit 1
		fi
		while IFS=$'\t' read -r image image_id; do
			[[ -n "$image" ]] || continue
			actual="$(docker image inspect --format '{{.Id}}' "$image" 2>/dev/null || true)"
			actual="sha256:${actual#sha256:}"
			if [[ "$actual" != "$image_id" ]]; then
				loaded_id="$(docker image inspect --format '{{.Id}}' "$image_id" 2>/dev/null || true)"
				loaded_id="sha256:${loaded_id#sha256:}"
				if [[ "$loaded_id" == "$image_id" ]] && docker image tag "$image_id" "$image"; then
					actual="$(docker image inspect --format '{{.Id}}' "$image" 2>/dev/null || true)"
					actual="sha256:${actual#sha256:}"
				fi
				if [[ "$actual" != "$image_id" ]]; then
					step_fail "aggregate bundle image reference/config ID mismatch for $image: expected $image_id, actual $actual" "Restore the verified release archive and re-import only after its manifest passes validation." "docker image inspect $(printf '%q' "$image")" "docker image inspect $(printf '%q' "$image_id")"
					end_report "Aggregate images were not accepted because manifest verification failed."
					exit 1
				fi
			fi
			step_ok "aggregate bundle image verified: $image"
		done < <(python3 - "$bundle_version_root/manifest.json" <<'PY'
import json
import sys
for image in json.load(open(sys.argv[1], encoding="utf-8"))["images"]:
	print(image["reference"] + "\t" + image["id"])
PY
)
		DEPENDENCY_PROFILE_DIR="$DEPENDENCY_BUNDLE_ROOT/profiles/$DEPENDENCY_BUNDLE_SHA256"
		if python3 "$REPO_ROOT/learner-vm/dependency_bundle.py" profiles --mode offline --root "$bundle_version_root" --working-cache-root "$working_cache_root" --output "$DEPENDENCY_PROFILE_DIR"; then
			step_ok "generated cache-only pip/Maven/npm/Go profiles at $DEPENDENCY_PROFILE_DIR"
			profile_file="$DEPENDENCY_PROFILE_DIR/profile.sh"
			managed_profile=/etc/profile.d/o11y-offline-profile.sh
			PROFILE_SELECTOR_TMP="$(mktemp "${TMPDIR:-/tmp}/o11y-profile.XXXXXX")" || PROFILE_SELECTOR_TMP=''
			if [[ -z "$PROFILE_SELECTOR_TMP" ]] || ! {
				printf '%s\n' '# Managed by learner-vm/scripts/60-load-images.sh; bundle profile is checksum-versioned.'
				printf 'if [ "$(id -un)" = %q ]; then\n  . %q\nfi\n' "$WORKSHOP_USER" "$profile_file"
			} > "$PROFILE_SELECTOR_TMP"; then
				step_fail "could not prepare the managed offline package-profile selector" "Check temporary-file space and permissions." "df -hP $(printf '%q' "${TMPDIR:-/tmp}")"
				end_report "Restore temporary storage before enabling package profiles."
				exit 1
			fi
			if [[ -e "$managed_profile" || -L "$managed_profile" ]]; then
				if [[ -f "$managed_profile" && ! -L "$managed_profile" ]] && [[ "$(head -n 1 "$managed_profile")" == '# Managed by learner-vm/scripts/60-load-images.sh; bundle profile is checksum-versioned.' ]]; then
					if cmp -s "$PROFILE_SELECTOR_TMP" "$managed_profile"; then
						step_ok "system login profile already selects this offline dependency bundle"
					elif install -o root -g root -m 0644 "$PROFILE_SELECTOR_TMP" "$managed_profile"; then
						step_ok "updated the managed system login profile selector to this verified bundle"
					else
						step_fail "could not update the managed dependency profile selector" "Check /etc/profile.d permissions; package caches remain intact." "ls -l $(printf '%q' "$managed_profile")"
						end_report "Restore managed profile installation permissions before continuing."
						exit 1
					fi
				else
					rm -f -- "$PROFILE_SELECTOR_TMP"
					PROFILE_SELECTOR_TMP=''
					step_fail "refusing to replace an unmanaged dependency profile" "Inspect $managed_profile and preserve other operators' shell configuration." "ls -l $(printf '%q' "$managed_profile")" "head -n 10 $(printf '%q' "$managed_profile")"
					end_report "Resolve the profile ownership conflict before enabling package-cache configuration."
					exit 1
				fi
			elif install -o root -g root -m 0644 "$PROFILE_SELECTOR_TMP" "$managed_profile"; then
				step_ok "installed cache-only profile selector for future login and build sessions"
			else
				rm -f -- "$PROFILE_SELECTOR_TMP"
				PROFILE_SELECTOR_TMP=''
				step_fail "could not install the managed dependency profile selector" "Check $DEPENDENCY_BUNDLE_ROOT permissions; package caches remain intact." "ls -ld $(printf '%q' "$DEPENDENCY_BUNDLE_ROOT")" "df -hP $(printf '%q' "$DEPENDENCY_BUNDLE_ROOT")"
				end_report "Restore profile installation permissions before continuing."
				exit 1
			fi
			rm -f -- "$PROFILE_SELECTOR_TMP"
			PROFILE_SELECTOR_TMP=''
			step_skip "new package requirements must be added to the bundle; PIP_NO_INDEX, Maven offline, npm offline and GOPROXY=file prevent public fallback" "interactive builds must use supported derived recipes/cache profiles"
		else
			step_fail "could not generate offline package-manager profiles" "Restore writable profile storage under $DEPENDENCY_BUNDLE_ROOT and retry." "ls -ld $(printf '%q' "$DEPENDENCY_BUNDLE_ROOT")"
			end_report "Keep the imported checksum-verified bundle and fix profile generation before building labs."
			exit 1
		fi
	fi
else
	step_skip "aggregate release bundle import is disabled because DEPENDENCY_BUNDLE_SHA256 is empty" "existing catalogued per-image workflow remains active"
fi

if build_bases="$(jq -r '.[] | .labs[]? | .commands[]? | select(.type == "build") | .base_images[]?' "$commands_file")"; then
	while IFS= read -r base || [[ -n "$base" ]]; do
		[[ -n "$base" ]] || continue
		if is_local_build_tag "$base" || [[ "$base" == localhost/* ]]; then continue; fi
		REQUIRED_IMAGES+=("$(normalize_image "$base")")
	done <<< "$build_bases"
else
	step_fail "could not read recorded build base images" "Install jq with script 20 and restore valid commands.json before preloading images." "command -v jq" "jq empty $(printf %q "$commands_file")"
	end_report "Correct the build metadata or jq installation before preparing base images."
	exit 1
fi

if [[ -s "$external_file" ]]; then
	while IFS= read -r image || [[ -n "$image" ]]; do
		image="${image%%#*}"
		image="$(printf '%s' "$image" | tr -d '[:space:]')"
		[[ -n "$image" ]] || continue
		REQUIRED_IMAGES+=("$(normalize_image "$image")")
	done < "$external_file"
fi

curated_images=$(python3 - "$REPO_ROOT/content/extracted/curated.json" <<'PY'
import json
import sys
with open(sys.argv[1], encoding="utf-8") as source:
    data = json.load(source)
images = set()
for track in data.values():
    for run in track.get("runs", []):
        if run.get("requires_k3s"):
            continue
        for key in ("image", "images"):
            value = run.get(key, [])
            if isinstance(value, str):
                value = [value]
            if isinstance(value, list):
                images.update(item for item in value if isinstance(item, str) and item)
print("\n".join(sorted(images)))
PY
)
while IFS= read -r image; do
	[[ -n "$image" ]] || continue
	if is_local_build_tag "$image" || [[ "$image" == localhost/* ]]; then REQUIRED_IMAGES+=("$image"); else REQUIRED_IMAGES+=("$(normalize_image "$image")"); fi
done <<< "$curated_images"
mapfile -t REQUIRED_IMAGES < <(printf '%s\n' "${REQUIRED_IMAGES[@]}" | sort -u)

if [[ -n "${DEPENDENCY_BUNDLE_SHA256:-}" && "$DRY_RUN" == false ]]; then
	missing_bundle_images=0
	for image in "${REQUIRED_IMAGES[@]}"; do
		if ! podman image exists "$image" >/dev/null 2>&1; then
			step_fail "required image is absent from the verified aggregate bundle: $image" "Recapture a bundle containing this exact lab/base reference; aggregate mode never falls back to a registry pull." "podman image inspect $(printf '%q' "$image")" "grep -F $(printf '%q' "$image") $(printf '%q' "$DEPENDENCY_BUNDLE_ROOT/$DEPENDENCY_BUNDLE_SHA256/manifest.json")"
			missing_bundle_images=1
		fi
	done
	if ((missing_bundle_images)); then
		end_report "The aggregate bundle is missing required lab images; no registry fallback was attempted."
		exit 1
	fi
fi

if ! load_image_archives podman; then
	end_report "Correct the local image archive described in MANUAL-FETCH.md Section C before retrying; no image pulls were attempted."
	exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
	log "external references are pulled through the configured Artifactory mirror; no image bundle transfer is required"
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]] || is_local_build_tag "$image"; then
			log "local manifest image is never pulled externally: $image"
		else
			log "would check rootful Podman store, then podman pull if missing: $image"
		fi
	done
else
	for tool in podman sha256sum; do
		if ! command -v "$tool" >/dev/null 2>&1; then
			step_fail "$tool is unavailable" "Run scripts/20-install-tooling.sh before loading workshop images." "command -v $(printf %q "$tool")" "rpm -q $(printf %q "$tool")"
		fi
	done
	rootless_state="$(podman info --format '{{.Host.Security.Rootless}}' 2>/dev/null || printf 'unknown')"
	if [[ "$rootless_state" == false ]]; then
		step_ok "Podman is using the rootful image store"
	else
		step_fail "Podman is not confirmed rootful (state: $rootless_state)" "Run through the script 50 wrapper using sudo and retain the shared rootful image store." "podman info --debug 2>&1 | tail -n 20" "id"
	fi
fi

if [[ "$DRY_RUN" == true ]]; then
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]]; then log "would build locally from its recorded context and verify exact manifest reference: $image"; fi
	done
	python3 -c '
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: data=json.load(source)
for track,track_data in data.items():
	for lab in track_data.get("labs",[]):
		for command in lab.get("commands",[]):
			if command.get("type") == "build":
				print("track={track} lab={lab} engine={engine} cwd={cwd} context={context} dockerfile={dockerfile} tag={tag} status={status}".format(track=track,lab=lab.get("file",""),engine=command.get("engine",""),cwd=command.get("cwd","."),context=command.get("context",""),dockerfile=command.get("dockerfile_arg") or command.get("dockerfile",""),tag=command.get("tag") or "<untagged>",status=command.get("preload_status","INTERACTIVE")))
				for step in command.get("preload_steps",[]): print("step="+step)
' "$commands_file" | while IFS= read -r build_line; do log "dry-run build $build_line"; done
fi

if [[ "$DRY_RUN" == false ]]; then
	OUTPUT_LOG=$(mktemp "${TMPDIR:-/tmp}/60-load-images.XXXXXX")
	IMAGE_REPORT_TMP=$(mktemp "${TMPDIR:-/tmp}/podman-images.XXXXXX")
	BUILT_TAGS_TMP=$(mktemp "${TMPDIR:-/tmp}/built-tags.XXXXXX")
	printf 'image | source | result | detail\n' > "$IMAGE_REPORT_TMP"
	printf 'track | lab | tag | status | source\n' > "$BUILT_TAGS_TMP"
	for image in "${REQUIRED_IMAGES[@]}"; do
		if [[ "$image" == localhost/* ]] || is_local_build_tag "$image"; then
			if podman image exists "$image" >/dev/null 2>&1; then
				step_ok "locally built manifest image is present: $image"
				printf '%s | manifest | present | exact local reference\n' "$image" >> "$IMAGE_REPORT_TMP"
			elif is_local_build_tag "$image"; then
				step_skip "recorded local build tag will be processed from commands.json" "$image"
			else
				if podman image exists "${image#localhost/}" >/dev/null 2>&1; then
					step_skip "local image exists only without manifest localhost prefix" "script 62 will import the existing tag and verify the original manifest reference: $image"
				else
					step_skip "local manifest image will be built from commands.json preload_steps" "$image"
				fi
			fi
		elif podman image exists "$image" >/dev/null 2>&1; then
			step_ok "external image already present: $image"
			source="${LOCAL_ARCHIVE_IMAGES[$image]:-existing store}"
			printf '%s | %s | present | original reference verified\n' "$image" "$source" >> "$IMAGE_REPORT_TMP"
			printf 'external | - | %s | present | %s\n' "$image" "$source" >> "$BUILT_TAGS_TMP"
		else
			if [[ -n "${DEPENDENCY_BUNDLE_SHA256:-}" ]]; then
				step_fail "aggregate bundle image disappeared before use: $image" "Re-import the verified bundle; registry fallback is disabled in aggregate mode." "podman image inspect $(printf '%q' "$image")"
				continue
			fi
			pull_log=$(mktemp "${TMPDIR:-/tmp}/60-pull.XXXXXX")
			if podman pull "$image" >"$pull_log" 2>&1; then
				step_ok "Podman pull command succeeded for $image"
				printf '%s | Artifactory mirror | pulled | command returned success\n' "$image" >> "$IMAGE_REPORT_TMP"
				printf 'external | - | %s | pulled | Artifactory mirror\n' "$image" >> "$BUILT_TAGS_TMP"
			else
				pull_status=$?
				if [[ -w "$LOG_FILE" || -w "$(dirname "$LOG_FILE")" ]]; then { printf '[%s] pull output for %s (exit %s)\n' "$SCRIPT_NAME" "$image" "$pull_status"; cat "$pull_log"; } >> "$LOG_FILE" 2>/dev/null || true; fi
				printf '%s | pull | failed | exit %s\n' "$image" "$pull_status" >> "$IMAGE_REPORT_TMP"
				printf 'external | - | %s | FAILED | Artifactory mirror\n' "$image" >> "$BUILT_TAGS_TMP"
				registry_pull_result "$image" "$pull_status" "$(cat "$pull_log")" 0 false
				step_skip "expected local image path: $MANUAL_FETCH_DIR/images/$(image_asset_name "$image")" "MANUAL-FETCH.md Section C recovery"
			fi
			rm -f -- "$pull_log"
			if ! podman image exists "$image" >/dev/null 2>&1; then
				step_fail "image is absent after local-archive loading and mirror pull: $image" "See MANUAL-FETCH.md Section C; stage $MANUAL_FETCH_DIR/images/$(image_asset_name "$image") and retry." "podman images --no-trunc"
			fi
		fi
	done

	while IFS= read -r record; do
		fields=$(python3 - "$record" <<'PY'
import json
import sys
item=json.loads(sys.argv[1])
print(item.get("track", ""))
print(item.get("lab", ""))
print(item.get("tag") or "")
print(item.get("preload_status", "INTERACTIVE"))
print(item.get("engine", ""))
print(item.get("cwd", "."))
print(item.get("context", ""))
print(item.get("dockerfile_arg") or item.get("dockerfile", ""))
print(item.get("raw", ""))
print(json.dumps(item.get("preload_steps", [])))
print(json.dumps(item.get("base_images", [])))
PY
)
		mapfile -t build_fields <<< "$fields"
		track="${build_fields[0]}"; lab="${build_fields[1]}"; tag="${build_fields[2]}"; status="${build_fields[3]}"; engine="${build_fields[4]}"; cwd="${build_fields[5]}"; context="${build_fields[6]}"; dockerfile="${build_fields[7]}"; raw="${build_fields[8]}"; steps_json="${build_fields[9]}"; bases_json="${build_fields[10]}"
		log "build record track=$track lab=$lab engine=$engine cwd=$cwd context=$context dockerfile=$dockerfile tag=${tag:-untagged}"
		if [[ "$status" == INTERACTIVE ]]; then
			base_images=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$bases_json")
			while IFS= read -r base; do
				[[ -n "$base" ]] || continue
				base="$(normalize_image "$base")"
				if podman image exists "$base" >/dev/null 2>&1; then
					step_ok "interactive build base image is preloaded: $base"
				else
					step_fail "interactive build base image is absent: $base" "Stage the catalogued archive at $MANUAL_FETCH_DIR/images/$(image_asset_name "$base") or restore Artifactory mirror access, then rerun script 60." "podman image exists $(printf %q "$base")" "grep -F $(printf %q "$base") $(printf %q "$external_file")"
				fi
			done <<< "$base_images"
			step_skip "interactive build was not invoked" "$track/$lab: $raw"
			printf '%s | %s | %s | INTERACTIVE (not run) | local build\n' "$track" "$lab" "${tag:-untagged}" >> "$BUILT_TAGS_TMP"
			continue
		fi
		if [[ "$status" != PRELOADABLE-VIA-VENDORED-CONTEXT && "$status" != PRELOADABLE-VIA-VENDORED-DOWNLOAD && "$status" != BUILT-PRELOADABLE ]]; then
			step_fail "build record has unsupported preload status $status" "Refresh commands.json with scripts/dev/parse-labs.py and inspect source record $track/$lab." "grep -n $(printf %q "$lab") $(printf %q "$commands_file")"
			((UNEXPECTED_BUILD_FAILURES += 1))
			continue
		fi
		if [[ -n "$tag" ]] && podman image exists "$tag" >/dev/null 2>&1; then
			step_ok "recorded preload tag is already present: $tag"
			printf '%s | %s | %s | ALREADY-PRESENT (build skipped) | existing store\n' "$track" "$lab" "$tag" >> "$BUILT_TAGS_TMP"
			continue
		fi
		base_images=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$bases_json")
		base_images_ready=true
		while IFS= read -r base; do
			[[ -n "$base" ]] || continue
			base="$(normalize_image "$base")"
			if is_local_build_tag "$base" || [[ "$base" == localhost/* ]]; then continue; fi
			if ! podman image exists "$base" >/dev/null 2>&1; then
				base_images_ready=false
				step_fail "base image required by $track/$lab is absent: $base" "Stage the catalogued archive at $MANUAL_FETCH_DIR/images/$(image_asset_name "$base") or restore Artifactory mirror access, then rerun script 60." "podman image exists $(printf %q "$base")" "grep -F $(printf %q "$base") $(printf %q "$external_file")"
			fi
		done <<< "$base_images"
		if [[ "$base_images_ready" != true ]]; then
			printf '%s | %s | %s | BASE-IMAGES-MISSING (build skipped) | local build\n' "$track" "$lab" "${tag:-untagged}" >> "$BUILT_TAGS_TMP"
			((UNEXPECTED_BUILD_FAILURES += 1))
			continue
		fi
		steps=$(python3 -c 'import json,sys; print("\n".join(json.loads(sys.argv[1])))' "$steps_json")
		if [[ -z "$steps" ]]; then
			step_fail "preloadable build has no recorded preload_steps: $track/$lab" "Regenerate commands.json with scripts/dev/parse-labs.py and inspect this build record." "grep -n $(printf %q "$lab") $(printf %q "$commands_file")"
			((UNEXPECTED_BUILD_FAILURES += 1))
			continue
		fi
		build_failed=false
		build_cwd="$REPO_ROOT/content/repos/$track/$cwd"
		while IFS= read -r build_step; do
			[[ -n "$build_step" ]] || continue
			if [[ "$build_step" == extract\ * ]]; then
				archive="${build_step#extract }"; archive="${archive%% to *}"
				destination_text="${build_step#* to }"; destination_text="${destination_text%% (archive root*}"
				archive_root="${build_step##*archive root }"; archive_root="${archive_root%)}"
				expected_archive_sha=$(python3 - "$manual_json" "$archive" <<'PY'
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: entries=json.load(source)
entry=next((row for row in entries if row.get("category")=="repo" and row.get("name")==sys.argv[2]),None)
print(entry.get("sha256", "") if entry else "")
PY
)
				archive_path="$REPO_ROOT/$archive"
				if [[ ! -s "$archive_path" || ! "$expected_archive_sha" =~ ^[0-9a-f]{64}$ ]]; then
					step_fail "runtime context archive is unavailable or unpinned: $archive" "Restore the repo ZIP and manual-fetch entry before building $track/$lab." "ls -l $(printf %q "$archive_path")" "grep -F $(printf %q "$archive") $(printf %q "$manual_json")"
					((UNEXPECTED_BUILD_FAILURES += 1))
					continue
				fi
				actual_archive_sha=$(sha256sum "$archive_path" | awk '{print $1}')
				if [[ "$actual_archive_sha" != "$expected_archive_sha" ]]; then
					step_fail "runtime context archive checksum mismatch: $archive" "Restore the verified archive from the repository ZIP." "sha256sum $(printf %q "$archive_path")" "grep -F $(printf %q "$archive") $(printf %q "$manual_json")"
					((UNEXPECTED_BUILD_FAILURES += 1))
					continue
				fi
				extract_dir="$REPO_ROOT/$destination_text"
				if unzip -tq "$archive_path" >/dev/null 2>&1 && unzip -oq "$archive_path" -d "$extract_dir"; then
					step_ok "verified and extracted runtime context archive root $archive_root for $track/$lab"
				else
					step_fail "could not extract verified runtime context archive $archive" "Check disk space and the archive root in commands.json." "unzip -t $(printf %q "$archive_path")" "df -hP $(printf %q "$extract_dir")"
					((UNEXPECTED_BUILD_FAILURES += 1))
				fi
			else
				if [[ "$build_step" == *"content/repos/"* ]]; then build_cwd="$REPO_ROOT"; fi
				if bash -c "cd $(printf %q "$build_cwd") && $build_step" >"$OUTPUT_LOG" 2>&1; then
					step_ok "preload build completed for $track/$lab: ${tag:-untagged}"
				else
					build_status=$?
					build_failed=true
					if [[ -w "$LOG_FILE" || -w "$(dirname "$LOG_FILE")" ]]; then { printf '[%s] build output for %s/%s command=%s (exit %s)\n' "$SCRIPT_NAME" "$track" "$lab" "$build_step" "$build_status"; cat "$OUTPUT_LOG"; } >> "$LOG_FILE" 2>/dev/null || true; fi
					printf 'BUILD FAILURE %s/%s tag=%s engine=%s cwd=%s status=%s command=%s\n' "$track" "$lab" "${tag:-untagged}" "$engine" "$cwd" "$build_status" "$build_step" >> "$IMAGE_REPORT_TMP"
					step_fail "preload build failed for $track/$lab: ${tag:-untagged} (exit $build_status)" "Inspect the vendored build context and original command recorded for $track/$lab; do not edit upstream sources during preload." "tail -n 15 $(printf %q "$OUTPUT_LOG")" "podman images --no-trunc | head -n 20"
					((UNEXPECTED_BUILD_FAILURES += 1))
				fi
			fi
		done <<< "$steps"
		if [[ "$build_failed" == true ]]; then
			printf '%s | %s | %s | BUILD-FAILED (see %s) | local build\n' "$track" "$lab" "${tag:-untagged}" "$LOG_FILE" >> "$BUILT_TAGS_TMP"
			continue
		fi
		if [[ -n "$tag" ]]; then
			if podman image exists "$tag" >/dev/null 2>&1; then
				printf '%s | %s | %s | %s | local build\n' "$track" "$lab" "$tag" "$status" >> "$BUILT_TAGS_TMP"
				printf '%s | build | present | %s %s\n' "$tag" "$track" "$lab" >> "$IMAGE_REPORT_TMP"
			else
				step_fail "recorded build did not produce tag $tag for $track/$lab" "Compare the exact preload_steps and source files in commands.json; interactive builds are not invoked." "podman image exists $(printf %q "$tag")" "tail -n 15 $(printf %q "$OUTPUT_LOG")"
				((UNEXPECTED_BUILD_FAILURES += 1))
			fi
		fi
	done < <(python3 - "$commands_file" <<'PY'
import json,sys
with open(sys.argv[1],encoding="utf-8") as source: data=json.load(source)
for track,track_data in data.items():
    for lab in track_data.get("labs",[]):
        for command in lab.get("commands",[]):
            if command.get("type")=="build":
                print(json.dumps({"track":track,"lab":lab.get("file",""),**command},separators=(",",":")))
PY
)

	manifest_path="$REPO_ROOT/content/repos/opentelemetry/_vendored/app_pod.yaml"
	manifest_image="$(awk '/^[[:space:]]*image:[[:space:]]*/ {sub(/^[[:space:]]*image:[[:space:]]*/, ""); print; exit}' "$manifest_path" 2>/dev/null || true)"
	if [[ -n "$manifest_image" ]]; then
		if podman image exists "$manifest_image" >/dev/null 2>&1; then
			step_ok "exact OpenTelemetry Pod manifest image exists in Podman: $manifest_image"
		elif podman image exists "${manifest_image#localhost/}" >/dev/null 2>&1; then
			local_source="${manifest_image#localhost/}"
			if run "podman tag $(printf %q "$local_source") $(printf %q "$manifest_image")" && podman image exists "$local_source" >/dev/null 2>&1 && podman image exists "$manifest_image" >/dev/null 2>&1; then
				step_ok "tagged the locally built image with the exact manifest reference $manifest_image"
			else
				step_fail "could not create/verify required manifest tag $manifest_image" "Use the exact local image source required by the vendored Pod manifest; preserve and verify both references." "podman image inspect $(printf %q "$local_source")" "podman image inspect $(printf %q "$manifest_image")" "grep -n 'image:' $(printf %q "$manifest_path")"
				((UNEXPECTED_BUILD_FAILURES += 1))
			fi
		else
			step_fail "OpenTelemetry Pod manifest image is absent: $manifest_image" "Build the recorded hello-otel:prog context and add the exact manifest reference; never try to pull localhost as external." "podman image exists $(printf %q "$manifest_image")" "grep -n 'image:' $(printf %q "$manifest_path")"
			((UNEXPECTED_BUILD_FAILURES += 1))
		fi
	fi

	install -o root -g root -m 0644 "$IMAGE_REPORT_TMP" "$REPO_ROOT/content/extracted/podman-load-report.txt"
	install -o root -g root -m 0644 "$BUILT_TAGS_TMP" "$REPO_ROOT/content/extracted/built-tags.txt"
	step_ok "wrote content/extracted/podman-load-report.txt and built-tags.txt"
fi

end_report "Review required image/build failures; after fixing them, continue with scripts/62-k3s-images.sh."
if ((UNEXPECTED_BUILD_FAILURES > 0)); then exit 2; fi
((FAIL_COUNT == 0))
