---
apiVersion: v1
kind: Service
metadata:
  name: echo-sink
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: echo-sink
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
