# v1: Inventory content files added, vendored, or transformed beyond the five upstream repo/docs sources.
import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CONTENT = ROOT / "content"
OUTPUT = CONTENT / "extracted" / "vendored-files.txt"
TRACKS = ("opentelemetry", "otel-developers", "prometheus", "fluentbit", "perses")
DETACHED_STAGE = "content/vendor/k3s/payload-stage/"


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def gitlab_sha(track):
    path = CONTENT / "repos" / track / ".source-sha"
    return path.read_text(encoding="utf-8").strip() if path.is_file() else "unknown"


def locked_source(relative):
    for line in (ROOT / "versions.lock").read_text(encoding="utf-8").splitlines():
        if f"path={relative}" not in line:
            continue
        source = next((field.removeprefix("source=") for field in line.split() if field.startswith("source=")), None)
        if source:
            return source
    return None


def classify(path):
    relative = path.relative_to(ROOT).as_posix()
    parts = path.relative_to(CONTENT).parts
    if relative == OUTPUT.relative_to(ROOT).as_posix():
        return None
    if relative.startswith(DETACHED_STAGE):
        return None
    if relative in ("content/vendor/MANUAL-FETCH.md", "content/vendor/manual-fetch.json"):
        return "n/a (generated by scripts/dev/generate-manual-fetch.py)", "Human and machine runtime-recovery catalogs generated from locked artifacts, inventories, and curated manifests."
    if relative == "content/vendor/README.md":
        return "n/a (operator documentation)", "Documents repository-resident inputs and runtime recovery."
    if relative == "content/vendor/k3s/SHA256SUMS":
        return "n/a (generated from versions.lock)", "Checksums for the small k3s inputs already present in the repository."
    if relative == "content/vendor/k3s/registry-probe.txt":
        return "n/a (generated by scripts/dev/vendor-k3s.sh)", "Online registry connectivity probe for the eight pinned k3s system images."
    if relative.startswith("content/vendor/k3s/") or relative.startswith("content/vendor/downloads/"):
        source = locked_source(relative)
        if source:
            reason = "Pinned k3s support input already present in the repository." if relative.startswith("content/vendor/k3s/") else "Pinned runtime build-context file already present in the repository."
            return source, reason
        return "n/a (generated by online vendor workflow)", "Generated vendor metadata; see versions.lock and scripts/dev/vendor-k3s.sh."
    if relative.endswith("content/repos/opentelemetry/_vendored/app_pod.yaml"):
        return "https://gitlab.com/o11y-workshops/intro-to-instrumentation/-/archive/v1.4/intro-to-instrumentation-v1.4.zip", "Podman-native Pod manifest referenced by the OpenTelemetry lab."
    if relative.startswith("content/repos/opentelemetry/_vendored/intro-to-instrumentation-v1.4/"):
        return "https://gitlab.com/o11y-workshops/intro-to-instrumentation/-/archive/v1.4/intro-to-instrumentation-v1.4.zip", "Vendored project build context required for the Podman-only hello-otel:prog run."
    if relative.startswith("content/repos/prometheus/_vendored/workshop-prometheus/"):
        return f"GitLab workshop repo HEAD {gitlab_sha('prometheus')} + extracted inline lab files", "Vendored Buildfile and configuration supplied as copy-and-paste snippets in lab02."
    if relative.endswith("node_modules/reveal.js-menu/menu.js"):
        return "https://registry.npmjs.org/reveal.js-menu/-/reveal.js-menu-2.1.0.tgz", "Repairs the missing reveal.js-menu v2.1.0 script referenced by otel-developers pages."
    if len(parts) >= 2 and parts[0] == "extracted":
        return "n/a (generated)", "Generated online-side extraction, review, or integrity report."
    if path.name == ".source-sha" and len(parts) >= 3 and parts[0] == "repos":
        return f"GitLab workshop repo HEAD {gitlab_sha(parts[1])}", "Records the source repository revision for the copied working tree."
    text = ""
    if path.suffix.lower() in (".html", ".htm"):
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            pass
    if "offline-lab-banner" in text or "--load removed: buildx-only flag" in text or "# PRELOADED — skip offline" in text:
        if parts[0] == "docs":
            return "upstream GitLab Pages mirror + offline patch", "Offline banner, preload pull markers, or Buildx flag note."
        if parts[0] == "repos":
            return f"GitLab workshop repo HEAD {gitlab_sha(parts[1])} + offline patch", "Offline banner, preload pull markers, or Buildx flag note."
    return None


def main():
    entries = []
    for path in sorted(item for item in CONTENT.rglob("*") if item.is_file()):
        classification = classify(path)
        if classification is None:
            continue
        source, reason = classification
        relative = path.relative_to(ROOT).as_posix()
        entries.append(f"{relative} | {source} | {sha256(path)} | {reason}")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(entries) + "\n", encoding="utf-8")
    print(f"{OUTPUT.relative_to(ROOT)}: {len(entries)} files inventoried (self-hash omitted to avoid recursion)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
